In [7]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
!pip install opencv-python
import cv2

img = cv2.imread(r'D:\ism study material\Fundamental of machine learning\LAB\image\BSE_Image.jpg')


In [8]:
print(img.shape)

(751, 1000, 3)


In [9]:
h, w, c = img.shape
print('width:',w)
print('height:',h)
print('channel:',c)


width: 1000
height: 751
channel: 3


In [10]:
img2=img.reshape((h*w,3))

In [11]:
img2

array([[255, 255, 255],
       [251, 251, 251],
       [253, 253, 253],
       ...,
       [255, 255, 255],
       [251, 251, 251],
       [253, 253, 253]], dtype=uint8)

In [12]:
from sklearn.mixture import GaussianMixture as GMM
#covariance choices, full, tied, diag, spherical
gmm_model= GMM(n_components=5,covariance_type='tied').fit(img2) #tied works better than full
gmm_labels=gmm_model.predict(img2)

In [13]:
gmm_labels

array([2, 2, 2, ..., 2, 2, 2], dtype=int64)

In [14]:
gmm_model.predict_proba(img2)


array([[4.44445171e-031, 1.19118983e-106, 1.00000000e+000,
        9.56983124e-065, 2.67806979e-148],
       [1.11018378e-028, 3.70160914e-102, 1.00000000e+000,
        2.78843556e-061, 5.59984332e-143],
       [7.02435633e-030, 2.09983789e-104, 1.00000000e+000,
        5.16573884e-063, 1.22461305e-145],
       ...,
       [4.44445171e-031, 1.19118983e-106, 1.00000000e+000,
        9.56983124e-065, 2.67806979e-148],
       [1.11018378e-028, 3.70160914e-102, 1.00000000e+000,
        2.78843556e-061, 5.59984332e-143],
       [7.02435633e-030, 2.09983789e-104, 1.00000000e+000,
        5.16573884e-063, 1.22461305e-145]])

In [15]:
original_shape = img.shape
segment= gmm_labels.reshape(original_shape[0], original_shape[1])

In [16]:
cv2.imwrite(r'D:\ism study material\Fundamental of machine learning\LAB\image\OutputSegment.jpg',segment)

True